---
- name: restart httpd
  service: name=httpd state=restarted

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart php-fpm
  service: name=php-fpm state=restarted

- name: restart mysql
  service: name=mysqld state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: restart sshd
  service: name=sshd state=restarted
